/*
** $Id: lua.c $
** Lua stand-alone interpreter
** See Copyright Notice in lua.h
*/

#define luna_c

#include "lprefix.h"


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <signal.h>

#include "lua.h"

#include "lauxlib.h"
#include "lualib.h"


#if !defined(LUNA_PROGNAME)
#define LUNA_PROGNAME		"lua"
#endif

#if !defined(LUNA_INIT_VAR)
#define LUNA_INIT_VAR		"LUNA_INIT"
#endif

#define LUNA_INITVARVERSION	LUNA_INIT_VAR LUNA_VERSUFFIX


static luna_State *globalL = NULL;

static const char *progname = LUNA_PROGNAME;


#if defined(LUNA_USE_POSIX)   /* { */

/*
** Use 'sigaction' when available.
*/
static void setsignal (int sig, void (*handler)(int)) {
  struct sigaction sa;
  sa.sa_handler = handler;
  sa.sa_flags = 0;
  sigemptyset(&sa.sa_mask);  /* do not mask any signal */
  sigaction(sig, &sa, NULL);
}

#else           /* }{ */

#define setsignal            signal

#endif                               /* } */


/*
** Hook set by signal function to stop the interpreter.
*/
static void lstop (luna_State *L, luna_Debug *ar) {
  (void)ar;  /* unused arg. */
  luna_sethook(L, NULL, 0, 0);  /* reset hook */
  lunaL_error(L, "interrupted!");
}


/*
** Function to be called at a C signal. Because a C signal cannot
** just change a Lua state (as there is no proper synchronization),
** this function only sets a hook that, when called, will stop the
** interpreter.
*/
static void laction (int i) {
  int flag = LUNA_MASKCALL | LUNA_MASKRET | LUNA_MASKLINE | LUNA_MASKCOUNT;
  setsignal(i, SIG_DFL); /* if another SIGINT happens, terminate process */
  luna_sethook(globalL, lstop, flag, 1);
}


static void print_usage (const char *badoption) {
  luna_writestringerror("%s: ", progname);
  if (badoption[1] == 'e' || badoption[1] == 'l')
    luna_writestringerror("'%s' needs argument\n", badoption);
  else
    luna_writestringerror("unrecognized option '%s'\n", badoption);
  luna_writestringerror(
  "usage: %s [options] [script [args]]\n"
  "Available options are:\n"
  "  -e stat   execute string 'stat'\n"
  "  -i        enter interactive mode after executing 'script'\n"
  "  -l mod    require library 'mod' into global 'mod'\n"
  "  -l g=mod  require library 'mod' into global 'g'\n"
  "  -v        show version information\n"
  "  -E        ignore environment variables\n"
  "  -W        turn warnings on\n"
  "  --        stop handling options\n"
  "  -         stop handling options and execute stdin\n"
  ,
  progname);
}


/*
** Prints an error message, adding the program name in front of it
** (if present)
*/
static void l_message (const char *pname, const char *msg) {
  if (pname) luna_writestringerror("%s: ", pname);
  luna_writestringerror("%s\n", msg);
}


/*
** Check whether 'status' is not OK and, if so, prints the error
** message on the top of the stack. It assumes that the error object
** is a string, as it was either generated by Lua or by 'msghandler'.
*/
static int report (luna_State *L, int status) {
  if (status != LUNA_OK) {
    const char *msg = luna_tostring(L, -1);
    l_message(progname, msg);
    luna_pop(L, 1);  /* remove message */
  }
  return status;
}


/*
** Message handler used to run all chunks
*/
static int msghandler (luna_State *L) {
  const char *msg = luna_tostring(L, 1);
  if (msg == NULL) {  /* is error object not a string? */
    if (lunaL_callmeta(L, 1, "__tostring") &&  /* does it have a metamethod */
        luna_type(L, -1) == LUNA_TSTRING)  /* that produces a string? */
      return 1;  /* that is the message */
    else
      msg = luna_pushfstring(L, "(error object is a %s value)",
                               lunaL_typename(L, 1));
  }
  lunaL_traceback(L, L, msg, 1);  /* append a standard traceback */
  return 1;  /* return the traceback */
}


/*
** Interface to 'luna_pcall', which sets appropriate message function
** and C-signal handler. Used to run all chunks.
*/
static int docall (luna_State *L, int narg, int nres) {
  int status;
  int base = luna_gettop(L) - narg;  /* function index */
  luna_pushcfunction(L, msghandler);  /* push message handler */
  luna_insert(L, base);  /* put it under function and args */
  globalL = L;  /* to be available to 'laction' */
  setsignal(SIGINT, laction);  /* set C-signal handler */
  status = luna_pcall(L, narg, nres, base);
  setsignal(SIGINT, SIG_DFL); /* reset C-signal handler */
  luna_remove(L, base);  /* remove message handler from the stack */
  return status;
}


static void print_version (void) {
  luna_writestring(LUNA_COPYRIGHT, strlen(LUNA_COPYRIGHT));
  luna_writeline();
}


/*
** Create the 'arg' table, which stores all arguments from the
** command line ('argv'). It should be aligned so that, at index 0,
** it has 'argv[script]', which is the script name. The arguments
** to the script (everything after 'script') go to positive indices;
** other arguments (before the script name) go to negative indices.
** If there is no script name, assume interpreter's name as base.
** (If there is no interpreter's name either, 'script' is -1, so
** table sizes are zero.)
*/
static void createargtable (luna_State *L, char **argv, int argc, int script) {
  int i, narg;
  narg = argc - (script + 1);  /* number of positive indices */
  luna_createtable(L, narg, script + 1);
  for (i = 0; i < argc; i++) {
    luna_pushstring(L, argv[i]);
    luna_rawseti(L, -2, i - script);
  }
  luna_setglobal(L, "arg");
}


static int dochunk (luna_State *L, int status) {
  if (status == LUNA_OK) status = docall(L, 0, 0);
  return report(L, status);
}


static int dofile (luna_State *L, const char *name) {
  return dochunk(L, lunaL_loadfile(L, name));
}


static int dostring (luna_State *L, const char *s, const char *name) {
  return dochunk(L, lunaL_loadbuffer(L, s, strlen(s), name));
}


/*
** Receives 'globname[=modname]' and runs 'globname = require(modname)'.
** If there is no explicit modname and globname contains a '-', cut
** the sufix after '-' (the "version") to make the global name.
*/
static int dolibrary (luna_State *L, char *globname) {
  int status;
  char *suffix = NULL;
  char *modname = strchr(globname, '=');
  if (modname == NULL) {  /* no explicit name? */
    modname = globname;  /* module name is equal to global name */
    suffix = strchr(modname, *LUNA_IGMARK);  /* look for a suffix mark */
  }
  else {
    *modname = '\0';  /* global name ends here */
    modname++;  /* module name starts after the '=' */
  }
  luna_getglobal(L, "require");
  luna_pushstring(L, modname);
  status = docall(L, 1, 1);  /* call 'require(modname)' */
  if (status == LUNA_OK) {
    if (suffix != NULL)  /* is there a suffix mark? */
      *suffix = '\0';  /* remove sufix from global name */
    luna_setglobal(L, globname);  /* globname = require(modname) */
  }
  return report(L, status);
}


/*
** Push on the stack the contents of table 'arg' from 1 to #arg
*/
static int pushargs (luna_State *L) {
  int i, n;
  if (luna_getglobal(L, "arg") != LUNA_TTABLE)
    lunaL_error(L, "'arg' is not a table");
  n = (int)lunaL_len(L, -1);
  lunaL_checkstack(L, n + 3, "too many arguments to script");
  for (i = 1; i <= n; i++)
    luna_rawgeti(L, -i, i);
  luna_remove(L, -i);  /* remove table from the stack */
  return n;
}


static int handle_script (luna_State *L, char **argv) {
  int status;
  const char *fname = argv[0];
  if (strcmp(fname, "-") == 0 && strcmp(argv[-1], "--") != 0)
    fname = NULL;  /* stdin */
  status = lunaL_loadfile(L, fname);
  if (status == LUNA_OK) {
    int n = pushargs(L);  /* push arguments to script */
    status = docall(L, n, LUNA_MULTRET);
  }
  return report(L, status);
}


/* bits of various argument indicators in 'args' */
#define has_error	1	/* bad option */
#define has_i		2	/* -i */
#define has_v		4	/* -v */
#define has_e		8	/* -e */
#define has_E		16	/* -E */


/*
** Traverses all arguments from 'argv', returning a mask with those
** needed before running any Lua code or an error code if it finds any
** invalid argument. In case of error, 'first' is the index of the bad
** argument.  Otherwise, 'first' is -1 if there is no program name,
** 0 if there is no script name, or the index of the script name.
*/
static int collectargs (char **argv, int *first) {
  int args = 0;
  int i;
  if (argv[0] != NULL) {  /* is there a program name? */
    if (argv[0][0])  /* not empty? */
      progname = argv[0];  /* save it */
  }
  else {  /* no program name */
    *first = -1;
    return 0;
  }
  for (i = 1; argv[i] != NULL; i++) {  /* handle arguments */
    *first = i;
    if (argv[i][0] != '-')  /* not an option? */
        return args;  /* stop handling options */
    switch (argv[i][1]) {  /* else check option */
      case '-':  /* '--' */
        if (argv[i][2] != '\0')  /* extra characters after '--'? */
          return has_error;  /* invalid option */
        *first = i + 1;
        return args;
      case '\0':  /* '-' */
        return args;  /* script "name" is '-' */
      case 'E':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_E;
        break;
      case 'W':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        break;
      case 'i':
        args |= has_i;  /* (-i implies -v) *//* FALLTHROUGH */
      case 'v':
        if (argv[i][2] != '\0')  /* extra characters? */
          return has_error;  /* invalid option */
        args |= has_v;
        break;
      case 'e':
        args |= has_e;  /* FALLTHROUGH */
      case 'l':  /* both options need an argument */
        if (argv[i][2] == '\0') {  /* no concatenated argument? */
          i++;  /* try next 'argv' */
          if (argv[i] == NULL || argv[i][0] == '-')
            return has_error;  /* no next argument or it is another option */
        }
        break;
      default:  /* invalid option */
        return has_error;
    }
  }
  *first = 0;  /* no script name */
  return args;
}


/*
** Processes options 'e' and 'l', which involve running Lua code, and
** 'W', which also affects the state.
** Returns 0 if some code raises an error.
*/
static int runargs (luna_State *L, char **argv, int n) {
  int i;
  for (i = 1; i < n; i++) {
    int option = argv[i][1];
    luna_assert(argv[i][0] == '-');  /* already checked */
    switch (option) {
      case 'e':  case 'l': {
        int status;
        char *extra = argv[i] + 2;  /* both options need an argument */
        if (*extra == '\0') extra = argv[++i];
        luna_assert(extra != NULL);
        status = (option == 'e')
                 ? dostring(L, extra, "=(command line)")
                 : dolibrary(L, extra);
        if (status != LUNA_OK) return 0;
        break;
      }
      case 'W':
        luna_warning(L, "@on", 0);  /* warnings on */
        break;
    }
  }
  return 1;
}


static int handle_luainit (luna_State *L) {
  const char *name = "=" LUNA_INITVARVERSION;
  const char *init = getenv(name + 1);
  if (init == NULL) {
    name = "=" LUNA_INIT_VAR;
    init = getenv(name + 1);  /* try alternative name */
  }
  if (init == NULL) return LUNA_OK;
  else if (init[0] == '@')
    return dofile(L, init+1);
  else
    return dostring(L, init, name);
}


/*
** {==================================================================
** Read-Eval-Print Loop (REPL)
** ===================================================================
*/

#if !defined(LUNA_PROMPT)
#define LUNA_PROMPT		"> "
#define LUNA_PROMPT2		">> "
#endif

#if !defined(LUNA_MAXINPUT)
#define LUNA_MAXINPUT		512
#endif


/*
** luna_stdin_is_tty detects whether the standard input is a 'tty' (that
** is, whether we're running lua interactively).
*/
#if !defined(luna_stdin_is_tty)	/* { */

#if defined(LUNA_USE_POSIX)	/* { */

#include <unistd.h>
#define luna_stdin_is_tty()	isatty(0)

#elif defined(LUNA_USE_WINDOWS)	/* }{ */

#include <io.h>
#include <windows.h>

#define luna_stdin_is_tty()	_isatty(_fileno(stdin))

#else				/* }{ */

/* ISO C definition */
#define luna_stdin_is_tty()	1  /* assume stdin is a tty */

#endif				/* } */

#endif				/* } */


/*
** luna_readline defines how to show a prompt and then read a line from
** the standard input.
** luna_saveline defines how to "save" a read line in a "history".
** luna_freeline defines how to free a line read by luna_readline.
*/
#if !defined(luna_readline)	/* { */

#if defined(LUNA_USE_READLINE)	/* { */

#include <readline/readline.h>
#include <readline/history.h>
#define luna_initreadline(L)	((void)L, rl_readline_name="lua")
#define luna_readline(L,b,p)	((void)L, ((b)=readline(p)) != NULL)
#define luna_saveline(L,line)	((void)L, add_history(line))
#define luna_freeline(L,b)	((void)L, free(b))

#else				/* }{ */

#define luna_initreadline(L)  ((void)L)
#define luna_readline(L,b,p) \
        ((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
        fgets(b, LUNA_MAXINPUT, stdin) != NULL)  /* get line */
#define luna_saveline(L,line)	{ (void)L; (void)line; }
#define luna_freeline(L,b)	{ (void)L; (void)b; }

#endif				/* } */

#endif				/* } */


/*
** Return the string to be used as a prompt by the interpreter. Leave
** the string (or nil, if using the default value) on the stack, to keep
** it anchored.
*/
static const char *get_prompt (luna_State *L, int firstline) {
  if (luna_getglobal(L, firstline ? "_PROMPT" : "_PROMPT2") == LUNA_TNIL)
    return (firstline ? LUNA_PROMPT : LUNA_PROMPT2);  /* use the default */
  else {  /* apply 'tostring' over the value */
    const char *p = lunaL_tolstring(L, -1, NULL);
    luna_remove(L, -2);  /* remove original value */
    return p;
  }
}

/* mark in error messages for incomplete statements */
#define EOFMARK		"<eof>"
#define marklen		(sizeof(EOFMARK)/sizeof(char) - 1)


/*
** Check whether 'status' signals a syntax error and the error
** message at the top of the stack ends with the above mark for
** incomplete statements.
*/
static int incomplete (luna_State *L, int status) {
  if (status == LUNA_ERRSYNTAX) {
    size_t lmsg;
    const char *msg = luna_tolstring(L, -1, &lmsg);
    if (lmsg >= marklen && strcmp(msg + lmsg - marklen, EOFMARK) == 0) {
      luna_pop(L, 1);
      return 1;
    }
  }
  return 0;  /* else... */
}


/*
** Prompt the user, read a line, and push it into the Lua stack.
*/
static int pushline (luna_State *L, int firstline) {
  char buffer[LUNA_MAXINPUT];
  char *b = buffer;
  size_t l;
  const char *prmt = get_prompt(L, firstline);
  int readstatus = luna_readline(L, b, prmt);
  if (readstatus == 0)
    return 0;  /* no input (prompt will be popped by caller) */
  luna_pop(L, 1);  /* remove prompt */
  l = strlen(b);
  if (l > 0 && b[l-1] == '\n')  /* line ends with newline? */
    b[--l] = '\0';  /* remove it */
  if (firstline && b[0] == '=')  /* for compatibility with 5.2, ... */
    luna_pushfstring(L, "return %s", b + 1);  /* change '=' to 'return' */
  else
    luna_pushlstring(L, b, l);
  luna_freeline(L, b);
  return 1;
}


/*
** Try to compile line on the stack as 'return <line>;'; on return, stack
** has either compiled chunk or original line (if compilation failed).
*/
static int addreturn (luna_State *L) {
  const char *line = luna_tostring(L, -1);  /* original line */
  const char *retline = luna_pushfstring(L, "return %s;", line);
  int status = lunaL_loadbuffer(L, retline, strlen(retline), "=stdin");
  if (status == LUNA_OK) {
    luna_remove(L, -2);  /* remove modified line */
    if (line[0] != '\0')  /* non empty? */
      luna_saveline(L, line);  /* keep history */
  }
  else
    luna_pop(L, 2);  /* pop result from 'lunaL_loadbuffer' and modified line */
  return status;
}


/*
** Read multiple lines until a complete Lua statement
*/
static int multiline (luna_State *L) {
  for (;;) {  /* repeat until gets a complete statement */
    size_t len;
    const char *line = luna_tolstring(L, 1, &len);  /* get what it has */
    int status = lunaL_loadbuffer(L, line, len, "=stdin");  /* try it */
    if (!incomplete(L, status) || !pushline(L, 0)) {
      luna_saveline(L, line);  /* keep history */
      return status;  /* cannot or should not try to add continuation line */
    }
    luna_pushliteral(L, "\n");  /* add newline... */
    luna_insert(L, -2);  /* ...between the two lines */
    luna_concat(L, 3);  /* join them */
  }
}


/*
** Read a line and try to load (compile) it first as an expression (by
** adding "return " in front of it) and second as a statement. Return
** the final status of load/call with the resulting function (if any)
** in the top of the stack.
*/
static int loadline (luna_State *L) {
  int status;
  luna_settop(L, 0);
  if (!pushline(L, 1))
    return -1;  /* no input */
  if ((status = addreturn(L)) != LUNA_OK)  /* 'return ...' did not work? */
    status = multiline(L);  /* try as command, maybe with continuation lines */
  luna_remove(L, 1);  /* remove line from the stack */
  luna_assert(luna_gettop(L) == 1);
  return status;
}


/*
** Prints (calling the Lua 'print' function) any values on the stack
*/
static void l_print (luna_State *L) {
  int n = luna_gettop(L);
  if (n > 0) {  /* any result to be printed? */
    lunaL_checkstack(L, LUNA_MINSTACK, "too many results to print");
    luna_getglobal(L, "print");
    luna_insert(L, 1);
    if (luna_pcall(L, n, 0, 0) != LUNA_OK)
      l_message(progname, luna_pushfstring(L, "error calling 'print' (%s)",
                                             luna_tostring(L, -1)));
  }
}


/*
** Do the REPL: repeatedly read (load) a line, evaluate (call) it, and
** print any results.
*/
static void doREPL (luna_State *L) {
  int status;
  const char *oldprogname = progname;
  progname = NULL;  /* no 'progname' on errors in interactive mode */
  luna_initreadline(L);
  while ((status = loadline(L)) != -1) {
    if (status == LUNA_OK)
      status = docall(L, 0, LUNA_MULTRET);
    if (status == LUNA_OK) l_print(L);
    else report(L, status);
  }
  luna_settop(L, 0);  /* clear stack */
  luna_writeline();
  progname = oldprogname;
}

/* }================================================================== */


/*
** Main body of stand-alone interpreter (to be called in protected mode).
** Reads the options and handles them all.
*/
static int pmain (luna_State *L) {
  int argc = (int)luna_tointeger(L, 1);
  char **argv = (char **)luna_touserdata(L, 2);
  int script;
  int args = collectargs(argv, &script);
  int optlim = (script > 0) ? script : argc; /* first argv not an option */
  lunaL_checkversion(L);  /* check that interpreter has correct version */
  if (args == has_error) {  /* bad arg? */
    print_usage(argv[script]);  /* 'script' has index of bad arg. */
    return 0;
  }
  if (args & has_v)  /* option '-v'? */
    print_version();
  if (args & has_E) {  /* option '-E'? */
    luna_pushboolean(L, 1);  /* signal for libraries to ignore env. vars. */
    luna_setfield(L, LUNA_REGISTRYINDEX, "LUNA_NOENV");
  }
  lunaL_openlibs(L);  /* open standard libraries */
  createargtable(L, argv, argc, script);  /* create table 'arg' */
  luna_gc(L, LUNA_GCRESTART);  /* start GC... */
  luna_gc(L, LUNA_GCGEN, 0, 0);  /* ...in generational mode */
  if (!(args & has_E)) {  /* no option '-E'? */
    if (handle_luainit(L) != LUNA_OK)  /* run LUNA_INIT */
      return 0;  /* error running LUNA_INIT */
  }
  if (!runargs(L, argv, optlim))  /* execute arguments -e and -l */
    return 0;  /* something failed */
  if (script > 0) {  /* execute main script (if there is one) */
    if (handle_script(L, argv + script) != LUNA_OK)
      return 0;  /* interrupt in case of error */
  }
  if (args & has_i)  /* -i option? */
    doREPL(L);  /* do read-eval-print loop */
  else if (script < 1 && !(args & (has_e | has_v))) { /* no active option? */
    if (luna_stdin_is_tty()) {  /* running in interactive mode? */
      print_version();
      doREPL(L);  /* do read-eval-print loop */
    }
    else dofile(L, NULL);  /* executes stdin as a file */
  }
  luna_pushboolean(L, 1);  /* signal no errors */
  return 1;
}


int main (int argc, char **argv) {
  int status, result;
  luna_State *L = lunaL_newstate();  /* create state */
  if (L == NULL) {
    l_message(argv[0], "cannot create state: not enough memory");
    return EXIT_FAILURE;
  }

  luna_gc(L, LUNA_GCSTOP);  /* stop GC while building state */
  luna_pushcfunction(L, &pmain);  /* to call 'pmain' in protected mode */
  luna_pushinteger(L, argc);  /* 1st argument */
  luna_pushlightuserdata(L, argv); /* 2nd argument */
  status = luna_pcall(L, 2, 1, 0);  /* do the call */
  result = luna_toboolean(L, -1);  /* get result */
  report(L, status);
  luna_close(L);
  return (result && status == LUNA_OK) ? EXIT_SUCCESS : EXIT_FAILURE;
}

